### ISSUE TITLE
Can't summon plugin once loaded

### ISSUE THREAD

**Issue by unamedplayer** [traefik/plugin-simplecache#15]
Well, I'm at a loss, I launch traefik with:

```
--experimental.plugins.plugin-simplecache.modulename=github.com/traefik/plugin-simplecache
--experimental.plugins.plugin-simplecache.version=v0.2.1
```

I confirmed it loaded:

`DEBU[2021-01-23T05:11:46Z] loading of plugin: cache: github.com/traefik/plugin-simplecache@v0.2.1`

but when I try to use it in a static config with:

```
  middlewares:
    my-plugin-simplecache:
        plugin:
            plugin-simplecache:
                path: /tmp
```

I end up with an odd type-less middleware:
<img width="578" alt="Screen Shot 2021-01-23 at 12 26 17 AM" src="https://user-images.githubusercontent.com/5199967/105569685-b8221280-5d11-11eb-8f82-f62d4836eb1b.png">

and the middleware isn't in effect in the router:
<img width="484" alt="Screen Shot 2021-01-23 at 12 27 54 AM" src="https://user-images.githubusercontent.com/5199967/105569703-e6075700-5d11-11eb-99e4-69733d263c64.png">

I've tried everything I could think of, hence my cry for help :) Any feedback or ideas very much appreciated, thank you!
