### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by AdriDevelopsThings** [traefik/plugin-simplecache#18]
Hey,

I installed the plugin, but when I make the request multiple types the header cache-status field is always: "miss":

traefik.yml
```
experimental:
  plugins:
    cache:
      modulename: "github.com/traefik/plugin-simplecache"
      version: "v0.2.1"
```

cache.yml
```
http:
  middlewares:
    regenbogen-ice-api-cache:
      plugin:
        cache:
          path: /cache/regenbogenice
          maxExpiry: 60
```

router
![image](https://user-images.githubusercontent.com/45321107/142917518-1c627a56-07b3-402f-9f51-7af740cb9e37.png)

and my requests:
![image](https://user-images.githubusercontent.com/45321107/142917756-8d2867d7-6b86-46d6-817a-3d5b935e6566.png)

I hope you can help me.
